- name: Gather controller facts
  hosts: controller
  gather_facts: yes
  any_errors_fatal: true

- name: Prepare and run Robot tests
  hosts: tester
  gather_facts: yes
  any_errors_fatal: true
  tasks:

      # TODO: remove once opendaylight jobs don't leave any residue (i.e.: routers) after running tempest tests
      - name: list overcloud resources - see whether there still are any leftovers
        shell: |
            . {{ ansible_user_dir }}/overcloudrc
            openstack server list --all-projects
            openstack network list
            openstack subnet list
            openstack floating ip list
            openstack port list
            openstack router list
            openstack stack list
            openstack keypair list
            openstack security group list

      - name: install required RPMs
        package:
            name: "{{ item }}"
            state: present
        become: yes
        with_items:
            - python-virtualenv
            - gcc
        tags: overcloud-cleanup

      - name: setup shade_janitor to purge openstack resources possibly left after tempest run
        git:
            accept_hostkey: yes
            version: master
            repo: https://github.com/yazug/shade_janitor
            dest: shade_janitor
        tags: overcloud-cleanup

      - name: Create robot virtualenv with latest pip, setuptools
        pip:
            virtualenv: "/tmp/robot-venv"
            name: "{{ item }}"
            state: present
        with_items:
            - setuptools
            - pip
        tags: overcloud-cleanup

      - name: install shade_janitor
        shell: |
            set -xe
            . /tmp/robot-venv/bin/activate
            cd shade_janitor
                pip install -U pip
                pip install -r requirements.txt >> pip_install_requirements.txt
                pip list > pip_list.txt
        tags: overcloud-cleanup

      - name: run shade_janitor to cleanup overcloud
        shell: |
            set -x
            . {{ ansible_user_dir }}/overcloudrc

            openstack project list
            export TEMPEST_PROJECT_IDS="$(openstack project list --column ID --column Name | awk -F'|' '$0 ~ /tempest/ {print $2}')"
            for _id in $TEMPEST_PROJECT_IDS; do
               openstack project purge --project $_id
            done

            # the very hardcore way but for the moment neither shade_janitor, nor openstack project purge can't do clean this mess properly
            # will do it this way till we can use CSIT's built int Openstack cleanup
            for port_id in $(openstack port list -f value | awk '{print $1}') ; do openstack port delete $port_id; done
            for fip_id in $(openstack floating ip list -f value | awk '{print $1}') ; do openstack floating ip delete $port_id; done
            for subnet_id in $(openstack subnet list -f value | awk '{print $1}') ; do openstack subnet delete $subnet_id; done
            for net_id in $(openstack network list -f value | awk '{print $1}') ; do openstack network delete $net_id; done
            for router_id in $(openstack router list -f value | awk '{print $1}') ; do openstack router delete $router_id; done

            SHADE_JANITOR_OPTS="--cleanup"

            . /tmp/robot-venv/bin/activate
            cd shade_janitor
            python shade_janitor/janitor.py $SHADE_JANITOR_OPTS --floatingips >> overcloud_cleanup.log
            sleep 10
            python shade_janitor/janitor.py $SHADE_JANITOR_OPTS >> overcloud_cleanup.log
        register: overcloud_cleanup
        until: overcloud_cleanup.rc == 0
        retries: 5
        delay: 5
        ignore_errors: true
        tags: overcloud-cleanup

      - name: list overcloud resources
        shell: |
            . {{ ansible_user_dir }}/overcloudrc
            openstack server list --all-projects
            openstack network list
            openstack subnet list
            openstack floating ip list
            openstack port list
            openstack router list
            openstack stack list
            openstack keypair list
            openstack security group list

      - name: Enable internal_api on tester
        become: true
        shell: |
            ip link add link eth1 name eth1.20 type vlan id 20
            ifconfig eth1.20 172.17.1.150/24 up
        tags: ha

      - name: set workdir fact
        set_fact:
            workdir: "{{ ansible_user_dir }}/robot"

      - name: set logdir, dockerdir, resultsdir facts
        set_fact:
            logdir: "{{ workdir }}/logs"
            dockerdir: "{{ workdir }}/docker"
            resultsdir: "{{ workdir }}/results"

      - name: recreate workdir
        file:
            path: "{{ workdir }}"
            state: "{{ item }}"
        with_items:
            - absent
            - directory

      - name: create logdir, dockerdir, resultsdir
        file:
            path: "{{ item }}"
            state: directory
        with_items:
            - "{{ logdir }}"
            - "{{ dockerdir }}"
            - "{{ resultsdir }}"

      - name: install or update required software
        package:
            name: docker
            state: latest

      - name: pull container image
        docker_image:
            name: "{{ test.container.image.name }}"
            state: "{{ item }}"
            force: yes
        with_items:
            - absent
            - present
        tags: container-image

      - name: update odl_test repository in docker container image
        shell: |
            echo "
            FROM {{ test.container.image.name }}
            RUN cd /home/opnfv/repos/odl_test/ && git pull origin master
            " > {{ dockerdir }}/Dockerfile
            docker tag {{ test.container.image.name }} {{ test.container.image.name }}_before_git_pull
            docker build -t {{ test.container.image.name }} {{ dockerdir }}

      - name: set fact for overcloudrc
        set_fact:
            overcloudrc: "{{ workdir }}/overcloudrc"

      - name: remove old overcloudrc
        file:
            path: "{{ overcloudrc }}"
            state: absent

      - name: make a copy of overcloudrc as we will have to tweak it
        shell: |
            cp -f ~stack/overcloudrc {{ overcloudrc }}

      - name: find IPs of OpenDaylight and OpenStack nodes
        shell: |
            source ~stack/stackrc
            OPENSTACK_SERVERS="$(openstack server list)"
            set -a
            ODL_IP=$(egrep no_proxy {{ overcloudrc }} | grep -o '[^,]*$')
            OPENSTACK_CONTROL_NODE_1_IP=$(echo "$OPENSTACK_SERVERS" | egrep controller-0 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
            OPENSTACK_CONTROL_NODE_2_IP=$(echo "$OPENSTACK_SERVERS" | egrep controller-1 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+') || true
            OPENSTACK_CONTROL_NODE_3_IP=$(echo "$OPENSTACK_SERVERS" | egrep controller-2 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+') || true
            OPENSTACK_COMPUTE_NODE_1_IP=$(echo "$OPENSTACK_SERVERS" | egrep compute-0 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
            OPENSTACK_COMPUTE_NODE_2_IP=$(echo "$OPENSTACK_SERVERS" | egrep compute-1 | egrep -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+') || true
            env | grep -E "ODL_IP|OPENSTACK_" >> {{ overcloudrc }}

      - name: make sure cirros guest images are available for use by the tests
        shell: |
            source {{ overcloudrc }}
            if ! openstack image list | grep cirros-0.3.4-x86_64-uec; then
              curl -o /tmp/cirros3.4.img http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
              glance image-create --name cirros-0.3.4-x86_64-uec --disk-format=qcow2 --container-format=bare --visibility=public --file=/tmp/cirros3.4.img
            fi
            if ! openstack image list | grep cirros-0.3.5-x86_64-disk; then
              curl -o /tmp/cirros3.5.img http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
              glance image-create --name cirros-0.3.5-x86_64-disk --disk-format=qcow2 --container-format=bare --visibility=public --file=/tmp/cirros3.5.img
            fi
            if ! openstack flavor list | grep m1.nano; then
              openstack flavor create --id 0 --vcpus 1 --ram 64 --disk 1 m1.nano
            fi

      - name: ODL Robot CSIT creates it's own external network, so delete it here beforehand
        shell: |
            source {{ overcloudrc }}
            if openstack network show nova; then
                openstack network delete nova
            fi

      - name: robot CSIT is complaining about using v3 for VOLUME_API, but v2 seems to be ok - fixing overcloudrc
        replace:
            path: "{{ overcloudrc }}"
            regexp: "OS_VOLUME_API_VERSION=.*"
            replace: "OS_VOLUME_API_VERSION=2"

      - name: copy overcloudrc file to controller node and more tweaks
        shell: |
            source {{ overcloudrc }}

            scp -i ~stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null \
                -o UserKnownHostsFile=/dev/null -o LogLevel=error \
                {{ overcloudrc }} heat-admin@$OPENSTACK_CONTROL_NODE_1_IP:/tmp/openrc

            # ODL Robot CSIT wants to use the ping command from the control node, so needs permissions
            ssh -i ~stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null \
                -o UserKnownHostsFile=/dev/null -o LogLevel=error \
                heat-admin@$OPENSTACK_CONTROL_NODE_1_IP "sudo chmod u+s `which ping`;"

            # Simulate an external internet address on the control node
            ssh -i ~stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null \
                -o UserKnownHostsFile=/dev/null -o LogLevel=error \
                heat-admin@$OPENSTACK_CONTROL_NODE_1_IP "sudo ip tuntap add dev internet_tap mode tap; \
                                                             sudo ifconfig internet_tap up 10.9.9.9/24;"

            # ODL Robot CSIT runs tempest tests from the control node, so installing that there
            ssh -i ~stack/.ssh/id_rsa -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null \
                -o UserKnownHostsFile=/dev/null -o LogLevel=error \
                heat-admin@$OPENSTACK_CONTROL_NODE_1_IP "sudo yum install -y openstack-tempest"

#      - name: prepare commands depending on deployment environment

      - name: run Robot
        shell: |
            set -x
            source {{ overcloudrc }}
            STACK_HOME=~stack
            robot_cmd="pybot \
                          --removekeywords wuks \
                          -c critical \
                          -e exclude \
                          -d {{ resultsdir }} \
                          -v BUNDLEFOLDER:/opt/opendaylight \
                          -v CONTROLLER_USER:heat-admin \
                          -v DEFAULT_LINUX_PROMPT:\$ \
                          -v DEFAULT_LINUX_PROMPT_STRICT:]\$ \
                          -v DEFAULT_USER:heat-admin \
                          -v DEVSTACK_DEPLOY_PATH:/tmp \
                          -v HA_PROXY_IP:$ODL_IP \
                          -v HA_PROXY_1_IP:$ODL_IP \
                          -v HA_PROXY_2_IP:$ODL_IP \
                          -v HA_PROXY_3_IP:$ODL_IP \
                          -v NUM_ODL_SYSTEM:{{ groups['controller'] | length }} \
                          -v NUM_OS_SYSTEM:3 \
                          -v NUM_TOOLS_SYSTEM:0 \
                          -v ODL_SNAT_MODE:controller \
                          -v ODL_STREAM:carbon \
                          -v ODL_SYSTEM_IP:$ODL_IP \
                          -v ODL_SYSTEM_1_IP:$ODL_IP \
                          -v OS_CONTROL_NODE_IP:$ODL_IP \
                          -v OS_CONTROL_NODE_1_IP:$OPENSTACK_CONTROL_NODE_1_IP \
                          -v OS_CONTROL_NODE_2_IP:$OPENSTACK_CONTROL_NODE_2_IP \
                          -v OS_CONTROL_NODE_3_IP:$OPENSTACK_CONTROL_NODE_3_IP \
                          -v OPENSTACK_BRANCH:stable/pike \
                          -v OS_COMPUTE_1_IP:$OPENSTACK_COMPUTE_NODE_1_IP \
                          -v OS_COMPUTE_2_IP:$OPENSTACK_COMPUTE_NODE_2_IP \
                          -v ODL_SYSTEM_IP:{{ hostvars['controller-0']['facter_ipaddress_vlan20'] }} \
                          -v ODL_SYSTEM_1_IP:{{ hostvars['controller-0']['facter_ipaddress_vlan20'] }} \
                          {%- if hostvars['controller-1']['facter_ipaddress_vlan20'] is defined %}
                          -v ODL_SYSTEM_2_IP:{{ hostvars['controller-1']['facter_ipaddress_vlan20'] | default('') }} \
                          {% endif %}
                          {%- if hostvars['controller-2']['facter_ipaddress_vlan20'] is defined %}
                          -v ODL_SYSTEM_3_IP:{{ hostvars['controller-2']['facter_ipaddress_vlan20'] | default('') }} \
                          {% endif %}
                          -v OS_USER:heat-admin \
                          -v ODL_ENABLE_L3_FWD:yes \
                          -v ODL_SYSTEM_USER:heat-admin \
                          -v ODL_SYSTEM_PROMPT:\$ \
                          -v PRE_CLEAN_OPENSTACK_ALL:True \
                          -v PUBLIC_PHYSICAL_NETWORK:datacentre \
                          -v RESTCONFPORT:8081 \
                          -v SECURITY_GROUP_MODE:stateful \
                          -v USER_HOME:/home/stack \
                          -v WORKSPACE:{{ workdir }}/workspace  \
                          -v USER:heat-admin \
                          -v TOOLS_SYSTEM_IP:localhost \
                          -v NODE_KARAF_COUNT_COMMAND:\"sudo docker exec opendaylight_api /bin/bash -c 'ps axf | grep org.apache.karaf | grep -v grep | wc -l' || echo 0\" \
                          -v NODE_START_COMMAND:\"sudo docker start opendaylight_api\" \
                          -v NODE_KILL_COMMAND:\"sudo docker stop opendaylight_api\" \
                          -v NODE_STOP_COMMAND:\"sudo docker stop opendaylight_api\" \
                          -v NODE_FREEZE_COMMAND:\"sudo docker stop opendaylight_api\" \
                          -v NODE_ROLE_INDEX_START:0 \
                          -v of_port:6653 "

            docker run -i --net=host -v {{ workdir }}:{{ workdir }}:Z \
                                     -v /home/stack/.ssh:/home/stack/.ssh:Z \
                                     -v $STACK_HOME:$STACK_HOME \
                                     -v {{ overcloudrc }}:{{ overcloudrc }} \
                                     {{ test.container.image.name }} \
                          /bin/bash -c "source {{ overcloudrc }}; \
                                        $robot_cmd {{ test.tests.replace(',', ' ') }};" \
                          2>&1 | tee -a {{ logdir }}/docker_run_$TEST_NAME.log
        tags: run-tests

      - name: Ensure results target directory exists
        file:
            dest: "{{ inventory_dir }}/../../../robot/"
            state: directory
        delegate_to: localhost

      - name: find results files
        find:
            paths: "{{ resultsdir }}"
            patterns: '*.xml,*.html'
            recurse: yes
        register: robot_results_files

      - name: Fetch results files
        fetch:
            src: "{{ item.path }}"
            dest: "{{ inventory_dir }}/../../../robot/"
            flat: yes
            fail_on_missing: no
        with_items: "{{ robot_results_files.files }}"
